name: Build KVM Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@v1.10.4
        with:
          kernel-url: https://github.com/${{ github.repository }}
          branch: thirteen
          config: vendor/gta4xlve_defconfig
          arch: arm64
          aosp-clang: true
          aosp-gcc: true
